const menu = [
    {
      id: 1,
      title: 'buttermilk pancakes',
      category: 'breakfast',
      price: 89,
      img: 'https://img.buzzfeed.com/thumbnailer-prod-us-east-1/51a9c5b156c84977ae50004b5ef622b2/finalFB.jpg?resize=1200:*',
      desc: `Our signature house-made buttermilk pancake, topped with whipped butter and served with Slopeside Pure Vermont Maple Syrup. `,
    },
    {
      id: 2,
      title: 'diner double',
      category: 'lunch',
      price: 199,
      img: 'https://laffahrestaurant.com/laffah_medai/2018/09/ALI_7031.jpg',
      desc: `The Double Diner has been offering signature Indian dishes, AMAZING pizzas and much more. `,
    },
    {
      id: 3,
      title: 'godzilla milkshake',
      category: 'shakes',
      price: 79,
      img: 'https://sf1.mariefranceasia.com/wp-content/uploads/sites/7/2015/11/Robert-Timms-490x410.jpg',
      desc: ` One of the drinks, “Milo Dinosaur” is topped with heaps of chocolate malt powder while the other, “Milo Godzilla” is topped with whipped cream and/or vanilla ice cream.`,
    },
    {
      id: 4,
      title: 'country delight',
      category: 'breakfast',
      price: 99,
      img: 'https://5.imimg.com/data5/MB/XN/GLADMIN-8301728/classic-delight-250x250.jpg',
      desc: `Delight For veggie lovers, loaded with Golden Baby corn, red bell pepper, crispy capsicum with 3 cheese combination. `,
    },
    {
      id: 5,
      title: 'egg attack',
      category: 'lunch',
      price: 150,
      img: 'https://domf5oio6qrcr.cloudfront.net/medialibrary/4579/eggs-heart-health.png',
      desc: `A layer of perfectly cooked egg on top of the legendary taste of India. Try the Shogun Burger today!`,
    },
    {
      id: 6,
      title: 'oreo dream',
      category: 'shakes',
      price: 49,
      img: 'https://topsecretrecipes.com/images/product/cheesecake-factory-oreo-dream-extreme-cheesecake-copycat-recipe.jpg',
      desc: `This Thick Oreo Milkshake is a delicious beverage made using Oreo cookies, whole milk, and vanilla ice cream.`,
    },
    {
      id: 7,
      title: 'bacon overflow',
      category: 'breakfast',
      price: 99,
      img: 'https://whenisdinner.com/wp-content/uploads/2019/06/Chicken-Bacon-Ranch-Poppers-Horiz.jpg',
      desc: `Bacon is a type of salt-cured pork made from various cuts, typically the belly or less fatty parts of the back. It is eaten as a side dish  `,
    },
    {
      id: 8,
      title: 'american classic',
      category: 'lunch',
      price: 250,
      img: 'https://us.123rf.com/450wm/dimasobko/dimasobko1711/dimasobko171100044/89133041-american-classic-lunch-eggs-burger-and-french-fries-at-plate.jpg',
      desc: `The classic American lunch: hamburgers, frankfurters, sandwiches macaroni and cheese casserole.`,
    },
    {
      id: 9,
      title: 'quarantine buddy',
      category: 'shakes',
      price: 149,
      img: 'https://www.rachaelrayshow.com/sites/default/files/styles/1100x620/public/images/2018-07/91cf0815868e49fd91babbc6444805a4.jpg?itok=3M4EABTz',
      desc: ` With the right level of chocolaty creaminess, this absolutely delectable Chocolate Milkshake for kids and adults brings together the perfect milkshake.`,
    },
  ];
  export default menu;